### ISSUE TITLE
Merging with react-async?

### ISSUE THREAD

**Issue by krishnagopinath** [slorber/react-async-hook#23]
First of all, thank you for the work you put into this awesome hook!

I am planning to use this package in my open source project [1] and was wondering about the long term plans for it. In your blog [2], you mention this:

> Note: it’s possible `react-async-hook` and `react-async` [3] will merge in the next months.

Is that happening? Would I be better off using `react-async` instead of your hook, for the sake of long term maintainability? 

What would you recommend? Thank you!

[1] https://github.com/Matterwiki/Matterwiki/tree/refactor-inception/
[2] https://sebastienlorber.com/Handling-API-request-race-conditions-in-React
[3] https://github.com/async-library/react-async

**Comment by slorber** [comment]
Hi,

Since then, react-query and swr have been released and became popular quite fast.

I'm planning to continue to maintain this lib, as I'm using it on customers projetcts. 

I want to make it the most simple abstraction to inject remote data into a component, by not supporting (on purpose) many things those other libs want to support.

Apart from small changes from the existing codebase, this lib is almost feature-complete, so if current state is good for you, you should be fine.

**Comment by krishnagopinath** [comment]
Thank you for the response, @slorber ! 

I definitely like this lib for the same reasons you described, it does one thing and one thing very well! 

I decided to use it in my project last night. Thanks again for this awesome lib!

**Comment by slorber** [comment]
thanks for using it :)
