### ISSUE TITLE
Conditional fetch

### ISSUE THREAD

**Issue by rckm** [slorber/react-async-hook#47]
How to conditionally fetch some data from api?

**Comment by slorber** [comment]
You can create multiple branch hierarchies in your React tree, on which you use different hooks.
This is somehow a workaround to be able to call any hood conditionally, but it might not work in all usecases.


Another possibility is to always call it, but make the async call return early instead of actually calling your API, cf the documented example:

```js
  const search = useAsyncAbortable(
    async (abortSignal, text) => {
      // If the input is empty, return nothing immediately (without the debouncing delay!)
      if (text.length === 0) {
        return [];
      }
      // Else we use the debounced api
      else {
        return debouncedSearchStarwarsHero(text, abortSignal);
      }
    },
    // Ensure a new request is made everytime the text changes (even if it's debounced)
    [inputText]
  );
```

Will add a simpler doc of this usecase in the FAQ
