### ISSUE TITLE
type of `asyncFunction` is not inferred as expected.

### ISSUE THREAD

**Issue by hanc1208** [slorber/react-async-hook#9]
```
const state = useAsync(async (id) => await doSomething(id), [id]);
```
`id` should be inferred as `string` but it is inferred as `any`.

**Comment by slorber** [comment]
Hi @hanc1208 

Actually those function overrides are useful to me, but I understand how it might be annoying for your usecase.

I want to support 2 versions of useAsync:


```jsx
const doSomething = async (arg: string) => { return arg };

const id = "1";

const state = useAsync(doSomething, [id]);
```

```jsx
const doSomething = async (arg: string) => { return arg };

const id = "1";

const state = useAsync(async () => {
  doSomething(id)
}, [id]);
```

It's important for me to always allow a no arg async function as argument, which gives more freedom. 

You might also want to trigger a refetch by using some item in the dependency array, yet this item does not necessarily need to be passed to the async function. 

```jsx
const state = useAsync(async () => {
  doSomething(id)
}, [id,someKeyToTriggerRefetchHere]);
```

So, I'd recommend that you just use this:

```jsx
const state = useAsync(async () => await doSomething(id), [id]);
```

or 

```jsx
const state = useAsync(doSomething, [id]);
```

Does this make sense to you? Do you see any drawback?

As is, I can't merge your PR because it removes the ability to always pass a no-arg function, which I actually need in my own apps ;)

**Comment by slorber** [comment]
> I think that ...args includes no args.

Can you please confirm that you can do the following with your PR?

```jsx
const state = useAsync(async () => {
  doSomething(id)
}, [id,someKeyToTriggerRefetchHere]);
```

Because as far as I remember I had to add the override because it wasn't the case. I needed the feature on my app. But maybe I'm wrong

**Comment by hanc1208** [comment]
I understood!

**Comment by slorber** [comment]
great, thanks :)
